apiVersion: v1
kind: Service
metadata:
  name: career-assistant-service
  namespace: career-assistant
  labels:
    app: career-assistant
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: career-assistant
  type: ClusterIP
