"""create_approval_requests_table

Revision ID: ec99ab373fe0
Revises: 7344c6e23ae5
Create Date: 2026-06-13 03:21:33.699821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID


# revision identifiers, used by Alembic.
revision: str = 'ec99ab373fe0'
down_revision: Union[str, None] = '7344c6e23ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('approval_token', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('approval_token')
    )
    op.create_index(op.f('ix_approval_requests_application_id'), 'approval_requests', ['application_id'], unique=False)
    op.drop_index('idx_app_logs_application_id', table_name='application_logs')
    op.drop_index('idx_app_logs_created_at', table_name='application_logs')
    op.create_index(op.f('ix_application_logs_application_id'), 'application_logs', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_logs_created_at'), 'application_logs', ['created_at'], unique=False)
    op.drop_index('idx_status_history_app_id', table_name='application_status_history')
    op.drop_index('idx_status_history_created_at', table_name='application_status_history')
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_created_at'), 'application_status_history', ['created_at'], unique=False)
    op.drop_index('idx_applications_queued_at', table_name='applications')
    op.drop_index('idx_applications_status', table_name='applications')
    op.drop_index('idx_applications_user_id', table_name='applications')
    op.drop_index('idx_applications_user_status', table_name='applications')
    op.drop_constraint('uq_applications_user_job', 'applications', type_='unique')
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.create_unique_constraint('uq_applications_user_job', 'applications', ['user_id', 'job_id'])
    op.create_index('idx_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_index('idx_applications_user_id', 'applications', ['user_id'], unique=False)
    op.create_index('idx_applications_status', 'applications', ['status'], unique=False)
    op.create_index('idx_applications_queued_at', 'applications', [sa.text('queued_at DESC')], unique=False)
    op.drop_index(op.f('ix_application_status_history_created_at'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.create_index('idx_status_history_created_at', 'application_status_history', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_status_history_app_id', 'application_status_history', ['application_id'], unique=False)
    op.drop_index(op.f('ix_application_logs_created_at'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_application_id'), table_name='application_logs')
    op.create_index('idx_app_logs_created_at', 'application_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_app_logs_application_id', 'application_logs', ['application_id'], unique=False)
    op.drop_index(op.f('ix_approval_requests_application_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
